application: pubsubhubbub
version: 1
runtime: python
api_version: 1

skip_files:
- ^(.*/)?app\.yaml
- ^(.*/)?app\.yml
- ^(.*/)?index\.yaml
- ^(.*/)?index\.yml
- ^(.*/)?#.*#
- ^(.*/)?.*~
- ^(.*/)?.*\.py[co].*
- ^(.*/)?.*/RCS/.*
- ^(.*/)?\..*
- ^(.*/)?(main_test|remote_shell|testutil|urlfetch_test_stub|feed_diff_test)\.py
- ^(.*/)?feed_diff_testdata

handlers:
- url: /base\.css
  static_files: base.css
  upload: base\.css
  secure: optional

- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico
  secure: optional

- url: /remote_api
  script: $PYTHON_LIB/google/appengine/ext/remote_api/handler.py
  login: admin
  secure: optional

# Optional bookmarklet creation gadget.
- url: /bookmarklet(_jsonp\.min\.js|\.min\.js|\.html|_config\.html|_gadget\.xml)
  static_files: bookmarklet/bookmarklet\1
  upload: bookmarklet/.+\.(min\.js|html|xml)
  secure: optional

# Always require the subscriber details form to be securely accessed.
- url: /subscription-details
  script: main.py
  secure: always

# Global stats are admin only.
- url: /stats
  script: main.py
  login: admin

# Mapreduce for running offline jobs.
- url: /mapreduce(/.*)?
  script: mapreduce/main.py
  login: admin

- url: .*
  script: main.py
  secure: optional
